#!/bin/sh

MIRROR_DEBIAN="http://mirror.webconverger.com/debian/"
MIRROR_SECURITY="http://ftp.de.debian.org/debian-security/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--debian-installer disabled \
	--bootappend-live "quiet homepage=http://portal.webconverger.com/ nonetworking nosudo splash vga=791" \
	-k 486 \
	-a i386 \
	--username webc \
	--hostname webconverger \
	-b usb-hdd \
	--categories "main contrib non-free" \
	--distribution lenny \
	--iso-publisher "Webconverger; http://webconverger.com/; support@webconverger.com" \
	--iso-volume "Webconverger $(date +%Y%m%d-%H:%M)" \
	--memtest none \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--packages-lists "chinese iceweasel-l10n japanese korean myspell printing webconverger" \
	${@}
