#!/bin/sh

MIRROR_DEBIAN="http://ftp.de.debian.org/debian/"
MIRROR_SECURITY="http://ftp.de.debian.org/debian-security/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--bootappend-live "quiet homepage=http://portal.webconverger.com/ nonetworking nosudo splash video=vesa:ywrap,mtrr vga=788 nopersistent quickreboot" \
	--cache-stages "bootstrap rootfs" \
	--debian-installer disabled \
	--debian-installer-distribution daily \
	-k 486 \
	-a i386 \
	-f minimal \
	-b usb-hdd \
	--apt apt \
	--username webc \
	--hostname webconverger \
	--bootloader syslinux \
	--categories "main contrib non-free" \
	--distribution lenny \
	--iso-publisher "Webconverger; http://webconverger.com/; support@webconverger.com" \
	--iso-volume "Webconverger $(date +%Y%m%d-%H:%M)" \
	--linux-packages "linux-image-2.6 aufs-modules-2.6" \
	--memtest none \
	--syslinux-splash config/binary_syslinux/splash.rle \
	--syslinux-timeout 5 \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-binary "http://cdn.debian.net/debian/" \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--binary-indices disabled \
	--packages-lists "webconverger" \
	--win32-loader disabled \
	${@}
