#!/bin/sh

# /usr/share/live-helper/hooks/minimal - hook list for live-helper(7)
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

echo Removing unused packages
for PACKAGE in apt-utils aptitude man-db manpages info libxapian15 vim-common vim-tiny \
	tcpd netcat-traditional gcc gcc-4.1 gcc-4.1-base gcc-4.2 gcc-4.2-base xserver-xorg-video-dummy ed dmidecode menu \
	iptables rsyslog nano
do
	if apt-get remove --purge --yes "${PACKAGE}"
	then
		apt-get autoremove --yes || true
	else
		echo "WARNING: ${PACKAGE} isn't installed"
	fi
done

apt-get clean

echo Removing unused files
find . -name *~ -print0 | xargs -0 rm -f

rm -rf /usr/include/*
rm -rf /usr/share/doc/*
rm -rf /usr/share/man/*
rm -rf /usr/share/info/*
rm -rf /usr/share/lintian/*
rm -rf /usr/share/linda/*
rm -rf /var/cache/man/*

echo Truncating logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done
