#!/bin/sh

set -eux

export DEB_BUILD_OPTIONS="nocheck"

# Install utilities for the rest of the build
apt-get update --yes
apt-get install --yes --no-install-recommends devscripts

cd "$(dirname "${0}")"
find $(pwd) -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort | while read X
do
	# Get package name from directory, stripping ordering prefix
	SRC="$(basename "${X}" | cut -b4-)"

	# Ge source
	case "${SRC}" in
	live-build)
		BACKPORT_FROM="jessie"
		;;
	*)
		BACKPORT_FROM="sid"
		;;
	esac

	# Install build-dependencies
	echo "deb-src http://httpredir.debian.org/debian ${BACKPORT_FROM} main" \
		> /etc/apt/sources.list.d/webconverger.list
	apt-get update --yes
	apt-get build-dep --yes ${SRC}

	# Clear build area
	rm -rf /tmp/buildd
	mkdir -p /tmp/buildd

	# Get source
	cd /tmp/buildd
	apt-get source ${SRC}
	cd */

	# Set changelog entry
	EDITOR=cat dch --local=+webconverger "Rebuild for Webconverger." -D unstable

	# Merge patch series
	if ls ${X}/*.patches >/dev/null 2>&1
	then
		find ${X} -name '*.patch' | LC_ALL=C sort | while read Y
		do
			mkdir -p debian/patches
			cp ${Y} debian/patches
			echo "$(basename "${Y}") -p1" >> debian/patches/series
		done
	fi

	# Build
	dpkg-buildpackage -uc -us

	# Install
	while read Y
	do
		dpkg -i ../${Y}_*.deb
	done < ${X}/install
done
