#!/bin/sh

lb config noauto --clean \
	--bootappend-live "homepage=http://webconverger.com hostname=webconverger nonetworking nopersistent quickreboot nomodeset splash vga=current quiet noroot" \
	--parent-mirror-chroot "http://cdn.debian.net/debian/" \
	--parent-mirror-binary "http://cdn.debian.net/debian/" \
	-k 486 \
	-a i386 \
	-b iso-hybrid \
	--hostname webconverger \
	--parent-archive-areas "main contrib non-free" \
	--mode progress --distribution artax \
	--debian-installer live \
	--syslinux-theme webc \
	--apt-indices false \
	--iso-publisher "http://webconverger.com" \
	--iso-volume "Webconverger" \
	--iso-application "Webconverger" \
	--archive-areas "main contrib non-free" \
	--apt-recommends false \
	--memtest none \
	--source false \
	--archives live \
	${@}
