#!/bin/sh

BOOTAPPEND=$(cat chroot/etc/webc/boot-cmdline | grep -v "^#" | head -n 1)

lb config noauto --clean \
	--bootappend-live "$BOOTAPPEND" \
	--parent-mirror-chroot "http://cdn.debian.net/debian/" \
	--parent-mirror-binary "http://cdn.debian.net/debian/" \
	--binary-filesystem fat16 \
	-k "486 686-pae" \
	-a i386 \
	--parent-archive-areas "main contrib non-free" \
	--mode progress-linux --distribution artax \
	--debian-installer false \
	--debian-installer-gui false \
	--apt-indices false \
	--iso-publisher "http://webconverger.com" \
	--iso-volume "Webconverger" \
	--iso-application "Webconverger" \
	--archive-areas "main contrib non-free" \
	--apt-recommends false \
	--memtest none \
	--source false \
	--archives live \
	${@}
