#!/bin/sh -e
grep -qs "locale=ja_JP.UTF-8" /proc/cmdline || exit 0
NOTTY="-q -y -o DPkg::Options::=--force-confdef"
DEBIAN_FRONTEND="noninteractive"
export DEBIAN_FRONTEND
PKGS="ttf-vlgothic scim-anthy scim-uim scim-skk scim-prime scim-canna scim-tables-ja iceweasel-l10n-ja"
logger "Setting up $0"
sleep 5
apt-get -q=2 update && apt-get ${NOTTY} install $PKGS
