#!/bin/sh

# /usr/share/live-helper/hooks/stripped - hook list for live-helper(7)
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Removing unused packages
# python-2.5
# Rip out X extensions
for PACKAGE in aptitude man-db manpages info dselect bsdmainutils manpages gcc-4.1 traceroute \
xserver-xorg-input-synaptics \
xserver-xorg-video-apm \
xserver-xorg-video-chips \
xserver-xorg-video-imstt \
xserver-xorg-video-mga \
xserver-xorg-video-neomagic \
xserver-xorg-video-newport \
xserver-xorg-video-nsc \
xserver-xorg-video-nv \
xserver-xorg-video-rendition \
xserver-xorg-video-s3 \
xserver-xorg-video-s3virge \
xserver-xorg-video-savage \
xserver-xorg-video-siliconmotion \
xserver-xorg-video-sisusb \
xserver-xorg-video-tdfx \
xserver-xorg-video-tga \
xserver-xorg-video-trident \
xserver-xorg-video-tseng \
xserver-xorg-video-v4l \
xserver-xorg-video-vga \
xserver-xorg-input-wacom \
xserver-xorg-video-ark \
xserver-xorg-video-cirrus \
xserver-xorg-video-cyrix \
xserver-xorg-video-dummy \
xserver-xorg-video-fbdev \
xserver-xorg-video-glint
do
	if ! apt-get remove --purge --yes "${PACKAGE}"
	then
		echo "WARNING: ${PACKAGE} isn't installed"
	fi
done

apt-get autoremove --yes || true

# Removing unused files
find . -name *~ | xargs rm -f

rm -rf /usr/include/*
rm -rf /usr/share/groff/*
rm -rf /usr/share/doc/*
rm -rf /usr/share/locale/*
rm -rf /usr/share/man/*
rm -rf /usr/share/i18n/*
rm -rf /usr/share/info/*
rm -rf /usr/share/lintian/*
rm -rf /usr/share/linda/*
rm -rf /usr/share/zoneinfo/*
rm -rf /var/cache/man/*

# Cleaning apt lists
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial

# Cleaning apt cache
rm -rf /var/cache/apt
mkdir -p /var/cache/apt/archives/partial

# Truncating logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done
