#!/bin/sh
# http://serverfault.com/questions/334967/how-do-you-find-current-internet-network-interface
cat /sys/class/net/$(for i in $(ip r); do echo $i; done | grep -A 1 -m 1 dev | tail -n1)/address > /tmp/MACID
wget -qO- --timeout=5 --post-data="M=$(md5sum /tmp/MACID |
awk '{print $1}')&V=$(cat /etc/webc/version)" http://ping.webconverger.org
