#!/bin/sh
server="http://ping.webconverger.org"
sleeping=5

test -f /etc/webc/version || exit

ping () {
	logger Pinging $1
	wget -qO- --timeout=5 --post-data="M=$(md5sum $1 |
	awk '{print $1}')&V=$(cat /etc/webc/version)" "$server"
}

mac=`mac_address`

while true
do
	if ping "$i"
	then
		logger Successful ping to "$server"
		exit
	else
		logger Failed to ping "$server", sleeping $sleeping seconds
	fi
	sleep $sleeping
done

done &
